const K="mymoney-v1";let S=JSON.parse(localStorage.getItem(K)||"null")||{title:"My Money",lang:"fa",accounts:[],tx:[],debts:[],goals:[],incomeGoal:0,expenseLimit:0},page="home";
const fa=()=>S.lang==="fa",T=(e,f)=>fa()?f:e,save=()=>localStorage.setItem(K,JSON.stringify(S)),usd=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0),id=()=>crypto.randomUUID();
function nav(){return `<div class="nav">${[["home","⌂","خانه"],["activity","☷","فعالیت"],["money","💵","مالی"],["goals","🎯","اهداف"],["settings","⚙","تنظیمات"]].map(x=>`<button onclick="go('${x[0]}')">${x[1]}<br>${T(x[1],x[2])}</button>`).join("")}</div>`}
function go(p){page=p;render()}function shell(c){document.getElementById("app").innerHTML=`<div class="wrap">${c}</div>${nav()}`}
function month(kind){let d=new Date();return S.tx.filter(x=>x.kind===kind&&new Date(x.date).getMonth()===d.getMonth()&&new Date(x.date).getFullYear()===d.getFullYear()).reduce((a,x)=>a+x.amount,0)}
function bal(a){let v=a.opening;S.tx.forEach(x=>{if(x.account===a.id){if(x.kind==="income")v+=x.amount;if(["expense","debt","goal"].includes(x.kind))v-=x.amount;if(x.kind==="transfer")v-=x.amount}if(x.kind==="transfer"&&x.to===a.id)v+=x.amount});return v}
function debt(d){return Math.max(0,d.original-S.tx.filter(x=>x.kind==="debt"&&x.debt===d.id).reduce((a,x)=>a+x.amount,0))}
function saved(g){return S.tx.filter(x=>x.kind==="goal"&&x.goal===g.id).reduce((a,x)=>a+x.amount,0)}
function prog(title,v,target){let p=Math.min(100,(v/Math.max(target,1))*100);return `<div class="card"><div class="row"><b>${title}</b><span>${p.toFixed(0)}%</span></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><small>${usd(v)} / ${usd(target)}</small></div>`}
function home(){let cash=S.accounts.reduce((a,x)=>a+bal(x),0),inc=month("income"),exp=month("expense"),db=S.debts.reduce((a,x)=>a+debt(x),0);shell(`<div class="top"><div><h1>${S.title}</h1><div class="muted">${new Date().toLocaleDateString(fa()?"fa-IR":"en-US",{dateStyle:"full"})}</div></div><button class="primary" onclick="addTx()">＋ ${T("Add","افزودن")}</button></div><div class="card"><div class="muted">${T("Available Money","پول قابل استفاده")}</div><div class="amount">${usd(cash)}</div></div><div class="grid"><div class="card">${T("Income","درآمد")}<br><b>${usd(inc)}</b></div><div class="card">${T("Expenses","هزینه")}<br><b>${usd(exp)}</b></div><div class="card">${T("Debt Remaining","بدهی باقی‌مانده")}<br><b>${usd(db)}</b></div><div class="card">${T("Net","خالص")}<br><b>${usd(inc-exp)}</b></div></div>${S.incomeGoal?prog(T("Income Goal","هدف درآمد"),inc,S.incomeGoal):""}${S.expenseLimit?prog(T("Expense Limit","سقف هزینه"),exp,S.expenseLimit):""}`)}
function addTx(){shell(`<h2>${T("Add Transaction","افزودن تراکنش")}</h2><form class="card form" onsubmit="return saveTx()"><select id="kind"><option value="income">${T("Income","درآمد")}</option><option value="expense">${T("Expense","هزینه")}</option><option value="transfer">${T("Transfer","انتقال")}</option><option value="debt">${T("Debt Payment","پرداخت بدهی")}</option><option value="goal">${T("Goal Savings","پس‌انداز هدف")}</option></select><input id="title" placeholder="${T("Title","عنوان")}"><input id="amount" type="number" step=".01" placeholder="${T("Amount USD","مبلغ دلار")}"><select id="account"><option value="">${T("Account","حساب")}</option>${S.accounts.map(a=>`<option value="${a.id}">${a.name}</option>`).join("")}</select><input id="date" type="datetime-local" value="${new Date().toISOString().slice(0,16)}"><button class="primary">${T("Save","ذخیره")}</button><button type="button" onclick="go('home')">${T("Cancel","لغو")}</button></form>`)}
function saveTx(){let a=+amount.value;if(!a)return false;S.tx.push({id:id(),kind:kind.value,title:title.value||kind.value,amount:a,date:new Date(date.value).toISOString(),account:account.value});save();go("activity");return false}
function activity(){let rows=S.tx.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(x=>`<div class="card row"><div><b>${x.title}</b><div class="muted">${new Date(x.date).toLocaleString()}</div></div><div>${x.kind==="income"?"+":"-"}${usd(x.amount)}<br><button class="danger" onclick="del('${x.id}')">🗑</button></div></div>`).join("");shell(`<div class="top"><h1>${T("Activity","فعالیت‌ها")}</h1><button class="primary" onclick="addTx()">＋</button></div>${rows||`<div class="card">${T("No transactions yet","هنوز تراکنشی ثبت نشده است")}</div>`}`)}
function del(i){S.tx=S.tx.filter(x=>x.id!==i);save();render()}
function moneyPage(){shell(`<h1>${T("Money","مدیریت مالی")}</h1><div class="card"><h2>${T("Accounts","حساب‌ها")}</h2>${S.accounts.map(a=>`<div class="row" style="padding:9px 0"><span>${a.name}</span><b>${usd(bal(a))}</b></div>`).join("")||T("No accounts","حسابی وجود ندارد")}<button class="primary" onclick="accountAdd()">＋ ${T("Add account","افزودن حساب")}</button></div><div class="card"><h2>${T("Debts","بدهی‌ها")}</h2>${S.debts.map(d=>`<div style="padding:9px 0"><b>${d.name}</b><br>${usd(debt(d))} ${T("remaining","باقی‌مانده")}</div>`).join("")||T("No debts","بدهی وجود ندارد")}<button class="primary" onclick="debtAdd()">＋ ${T("Add debt","افزودن بدهی")}</button></div>`)}
function accountAdd(){let n=prompt(T("Account name","نام حساب")),v=prompt(T("Opening balance","موجودی اولیه"));if(n){S.accounts.push({id:id(),name:n,opening:+v||0});save();render()}}
function debtAdd(){let n=prompt(T("Debt name","نام بدهی")),v=prompt(T("Original amount","مبلغ اولیه"));if(n){S.debts.push({id:id(),name:n,original:+v||0});save();render()}}
function goals(){shell(`<div class="top"><h1>${T("Goals","اهداف")}</h1><button class="primary" onclick="goalAdd()">＋</button></div>${S.goals.map(g=>prog(g.name,saved(g),g.target)).join("")||`<div class="card">${T("No goals yet","هنوز هدفی ثبت نشده است")}</div>`)}
function goalAdd(){let n=prompt(T("Goal name","نام هدف")),v=prompt(T("Target amount","مبلغ هدف"));if(n){S.goals.push({id:id(),name:n,target:+v||0});save();render()}}
function settings(){shell(`<h1>${T("Settings","تنظیمات")}</h1><div class="card form"><label>${T("App name","نام برنامه")}<input id="appn" value="${S.title}"></label><label>${T("Language","زبان")}<select id="lang"><option value="fa" ${fa()?"selected":""}>فارسی</option><option value="en" ${!fa()?"selected":""}>English</option></select></label><label>${T("Monthly income goal","هدف درآمد ماهانه")}<input id="ig" type="number" value="${S.incomeGoal}"></label><label>${T("Monthly expense limit","سقف هزینه ماهانه")}<input id="el" type="number" value="${S.expenseLimit}"></label><button class="primary" onclick="settingsSave()">${T("Save","ذخیره")}</button></div>`)}
function settingsSave(){S.title=appn.value||"My Money";S.lang=lang.value;S.incomeGoal=+ig.value||0;S.expenseLimit=+el.value||0;save();render()}
function render(){if(page==="home")home();else if(page==="activity")activity();else if(page==="money")moneyPage();else if(page==="goals")goals();else settings()}render();